### ISSUE TITLE
Unclear Documentation

### ISSUE THREAD

**Issue by ddinh0411** [YallowMan/TaskFlow#1]
Hi there, I'm having an issue with the project. So it's a little unclear on your documentation specifically for how to build the project on my local machine and how to test your code. If you could tell me what I would need to get your project built on my end and what I can expect when testing that would be great. If there's also anything that you would like to see as a contribution I can see if I can implement it from my end.

**Comment by emilynguyenl** [comment]
When you clone the repo onto your machine, all of the source code should be in the /src file. Currently, we have custom_blocks.js, index.html, and styles.css. To test the code, you can make changes and then push it to github. The code should show up on this URL: https://yallowman.github.io/TaskFlow/src. For testing purposes, there are blocks for creating a task in the "Task" toolbox, you can put your own text as well. We are currently have issues with the "Run JavaScript" button, but the "Generate JavaScript" button should work. Please let us know if you have any further questions!

**Comment by ddinh0411** [comment]
Just to clarify, so you do not have an external IDE that you're checking your code in. Just need to know if I need to install another package or program to be able to test and run your code on my end and not through your repo.

**Comment by emilynguyenl** [comment]
No. We don't have an external IDE, just the repo.
