### ISSUE TITLE
Blockly Workspace Window Size

### ISSUE THREAD

**Issue by masli747** [YallowMan/TaskFlow#2]
Hello All,

I'm currently having an issue with the size of the Blockly section on your preview webpage. It can become cramped, especially when the sub-menus are opened. I also think the default window size is a little small, even when nothing is open.

I was wondering if this is intended behavior, or if there are any plans to change this? I'm also happy to try experimenting with this for with a pull request if this sounds interesting to you!

Thank You!

**Comment by YallowMan** [comment]
This was planned to change but didn't really have an exact idea of it. This does sound interesting though and please feel free to experiment with it because it is something we'd like to look at.
