### ISSUE TITLE
Code Not Working

### ISSUE THREAD

**Issue by EthanClunie** [YallowMan/TaskFlow#3]
Hey, I'm trying to get the code running so I can test the Blockly front-end in my browser but I can't get it running. I am unsure how to get this working and there isn't any documentation that explains how to build, run, or test this project. If you guys could provide some instructions for how I can actually run and test your project, that would be great.

**Comment by emilynguyenl** [comment]
When you clone the repo onto your machine, all of the source code should be in the /src file. Currently, we have custom_blocks.js, index.html, and styles.css. To test the code, you can make changes and then push it to github. The code should show up on this URL: https://yallowman.github.io/TaskFlow/src. For testing purposes, there are blocks for creating a task in the "Task" toolbox, you can put your own text as well. We are currently have issues with the "Run JavaScript" button, but the "Generate JavaScript" button should work. Please let us know if you have any further questions!
