### ISSUE TITLE
Missing DB Implementation

### ISSUE THREAD

**Issue by MaxSChapman** [YallowMan/TaskFlow#4]
Your project and block designs mentions some database implementation, but I did not find anything of the sort.  How are we to review that? Are you currently just generating the code from the blocks and pasting it into some other program to simulate DB usage? I see no way to do that with your current codebase.

**Comment by YallowMan** [comment]
I don't think you would be able to review the DB implementation just yet as it hasn't necessarily been added yet nor have we done anything with Databases although it is planned to be done. Currently we haven't had a way to simulate DB usage either in some program.
